In [1]:
# setup - installing guidebox
!pip install guidebox
!pip install ipywidgets

Requirement already satisfied: guidebox in /opt/conda/lib/python3.7/site-packages (1.0.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from guidebox) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests->guidebox) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from requests->guidebox) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->guidebox) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests->guidebox) (2019.6.16)
Requirement already satisfied: ipywidgets in /opt/conda/lib/python3.7/site-packages (7.5.1)
Requirement already satisfied: nbformat>=4.2.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets) (4.4.0)
Requirement already satisfied: traitlets>=4.3.1 in /opt/conda/lib/python3.7/site-packages (from ipywidgets) (4.3.2)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in /opt/conda/lib/python3.7/site-packages (from ipywidgets) (7.5.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.7/site-packages (from ipywidgets) (5.1.0)
Requirement already satisfied: ipython_genutils in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets) (3.0.1)
Requirement already satisfied: jupyter_core in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets) (4.4.0)
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from traitlets>=4.3.1->ipywidgets) (1.12.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.7/site-packages (from traitlets>=4.3.1->ipywidgets) (4.4.0)
Requirement already satisfied: backcall in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.1.0)
Requirement already satisfied: jedi>=0.10 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.13.3)
Requirement already satisfied: pygments in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (2.4.0)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (2.0.9)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (41.0.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (4.7.0)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.7.5)
Requirement already satisfied: notebook>=4.4.1 in /opt/conda/lib/python3.7/site-packages (from widgetsnbextension~=3.5.0->ipywidgets) (5.7.8)
Requirement already satisfied: jupyter-client in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets) (5.2.4)
Requirement already satisfied: tornado>=4.2 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets) (6.0.2)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets) (19.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets) (0.15.2)
Requirement already satisfied: parso>=0.3.0 in /opt/conda/lib/python3.7/site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.4.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.7/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.1.7)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.6.0)
Requirement already satisfied: terminado>=0.8.1 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.8.2)
Requirement already satisfied: Send2Trash in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.5.0)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (2.10.1)
Requirement already satisfied: pyzmq>=17 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (18.0.1)
Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.6.0)
Requirement already satisfied: nbconvert in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (5.5.0)
Requirement already satisfied: python-dateutil>=2.1 in /opt/conda/lib/python3.7/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets) (2.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.7/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.1.1)
Requirement already satisfied: defusedxml in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.5.0)
Requirement already satisfied: testpath in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.4.2)
Requirement already satisfied: bleach in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (3.1.0)
Requirement already satisfied: mistune>=0.8.1 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.8.4)
Requirement already satisfied: entrypoints>=0.2.2 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.4.2)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.5.1)

In [2]:
# setup - importing programs by alphabetical order
import csv
import guidebox
from IPython.core.display import HTML
from IPython.display import Image
import json
# import numpy as np
import pandas as pd
import requests

In [3]:
# importing cvs file to get list of two-letter country codes
dic = {}
with open('wikipedia-iso-country-codes.csv') as f: # opening the file
    file = csv.DictReader(f, delimiter=',')
    for line in file:
        dic[line['English short name lower case']] = line['Alpha-2 code']
        
# set region
print('Enter the country where you are currently streaming or watching television.')
country = input('Where are you watching? ') # user can selection a region
try:
    dic[country] # if the user entered a valid region, then there should be a corresponding key-value pair
    guidebox.region = "%s" % (dic[country]) # setting the matching value - the two-letter country code - as the region
    print('The region is set as: %s' % (guidebox.region))
except KeyError:
    print('That is not a valid region. Please try again.')

Enter the country where you are currently streaming or watching television.
Where are you watching? Cuba
The region is set as: CU

In [4]:
#api key
guidebox.api_key = 'b6b51fbc578321cbd4966880cbce6ea9537a9ce4'

In [5]:
# example request - movies and only 3 results
# guidebox outputs do not need to be de-serialized because they are already in .json format
# results are listed by popularity
movies = guidebox.Movie.list(limit=10) 

# extracting data from variable movies to put into a legible format 
# initilazing variables
data = {}
titles = []
ratings = []
release_dates = []
theaters = []
i = 0

#for loop to read through the json object and assign words to lists
for i in range(0,10):
    titles.append(movies['results'][i]['original_title'])
    ratings.append(movies['results'][i]['rating'])
    release_dates.append(movies['results'][i]['release_date'])
    theaters.append(movies['results'][i]['in_theaters'])
    i += 1

#creating key-value pairs
data = {'Titiles': titles, 'Rating': ratings, 'Release Date': release_dates, 'Still in Theaters?': theaters}

#creating a dataframe and printing the dataframe
data_df = pd.DataFrame(data)
data_df

                         Titiles Rating Release Date  Still in Theaters?
0                   The Irishman     NR   2019-11-01                True
1  Once Upon a Time in Hollywood      R   2019-07-25                True
2                   Ready or Not      R   2019-08-21               False
3                       Hustlers     NR   2019-09-12                True
4                          Klaus     NR   2019-11-15               False
5                         Frozen     PG   2013-11-27               False
6    The Knight Before Christmas     NR   2019-11-21               False
7                It: Chapter Two      R   2019-09-04                True
8                       The King     NR   2019-10-11               False
9               Angel Has Fallen      R   2019-08-21               False

In [6]:
# example request - shows from a specific channel and only 10 results
# this function would be used in conjunction with the TV DB API
channel = input('What channel would you like to view? ') # user enters channel name
shows = guidebox.Show.list(channel=channel, limit=10)

data2 = {}
titles2 = []
id = []
i = 0

#for loop to read through the json object and assign words to lists
for i in range(0,10):
    titles2.append(shows['results'][i]['title'])
    id.append(shows['results'][i]['id'])
    i += 1
    
#creating key-value pairs
data2 = {'Titles': titles2, 'Show ID': id}

#creating a dataframe and printing the dataframe
data_df2 = pd.DataFrame(data2)
data_df2

What channel would you like to view? hbo

               Titles  Show ID
0  His Dark Materials    56315
1            Watchmen    56033
2     Game of Thrones     6959
3      Silicon Valley    18321
4           Westworld    38948
5        The Sopranos     6969
6      True Detective    17205
7            The Wire     7135
8          True Blood     6965
9       The Leftovers    18948

In [7]:
# example request - retrieve a single show
show = guidebox.Show.retrieve(id=1253)
show_data = {'Title': show['title'], 'Genre': show['genres'][0]['title'], 'Synopsis': show['overview'], 
             'Channel': show['channels'][0]['name'], 'Air Date': show['air_day_of_week'], 
             'Air Time': show['air_time']}
index = [0]
show_df = pd.DataFrame(show_data, index)
show_df

,Title,Genre,Synopsis,Channel,Air Date,Air Time
0,That '70s Show,Comedy,Set in the Wisconsin suburbs of the United Sta...,MTV,Thursday,8:00 PM

In [8]:
# testing search function - returns a list of titles that match the query
title = input('What is the name of the celebrity, actor/actress, or director you are looking for? ')
person = guidebox.Search.person(query=title)
person['results'][0]['name']
person_photo = Image(url = person['results'][0]['images']['medium']['url'], width=person['results'][0]['images']['medium']['width'], height=person['results'][0]['images']['medium']['height']) 
person_photo

What is the name of the celebrity, actor/actress, or director you are looking for? Mila Kunis